// Code generated by mockery v2.14.1. DO NOT EDIT.

package mocks

import (
	datadragon "github.com/KnutZuidema/golio/datadragon"
	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// GetAllLoLChampions provides a mock function with given fields:
func (_m *Client) GetAllLoLChampions() ([]datadragon.ChampionDataExtended, error) {
	ret := _m.Called()

	var r0 []datadragon.ChampionDataExtended
	if rf, ok := ret.Get(0).(func() []datadragon.ChampionDataExtended); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]datadragon.ChampionDataExtended)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLoLChampion provides a mock function with given fields: championName
func (_m *Client) GetLoLChampion(championName string) (datadragon.ChampionDataExtended, error) {
	ret := _m.Called(championName)

	var r0 datadragon.ChampionDataExtended
	if rf, ok := ret.Get(0).(func(string) datadragon.ChampionDataExtended); ok {
		r0 = rf(championName)
	} else {
		r0 = ret.Get(0).(datadragon.ChampionDataExtended)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(championName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewClient(t mockConstructorTestingTNewClient) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
